"""change the length of the admin password hash

Revision ID: 629d36f3c787
Revises: cfdc7c9e934c
Create Date: 2025-04-08 15:44:22.197568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629d36f3c787'
down_revision = 'cfdc7c9e934c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
